### ISSUE TITLE
OpenCV Cutting out the Sky

### ISSUE THREAD

**Issue by khlam** [Aerolyzer/Aerolyzer#107]
The purpose of cutting out the sky in an acceptable image is to isolate sections of the sky to perform Aerosol analysis.

Draft of function select_sky() currently located here: https://github.com/lamki866/Aerolyzer/blob/get_sky/aerolyzer/image_restriction_functions.py
This is a conversion of horizon detection by threshold. For a full explanation on how the sky threshold detection works please reference https://github.com/Aerolyzer/Aerolyzer/issues/96

Note: To support transparency we need to convert from .jpg to .png

The following images are produced by my draft code.

Example 1
Input:
 ![90](https://user-images.githubusercontent.com/4841220/34967280-5edf58a6-fa16-11e7-8093-75ec2534b0c1.jpg)

Output:
![90-skycut](https://user-images.githubusercontent.com/4841220/34967288-683982fa-fa16-11e7-8f22-2a4e2775d4d6.png)

Example 2:
Input:
![136](https://user-images.githubusercontent.com/4841220/34967298-7e7c22de-fa16-11e7-9f5c-d4d9840ed779.jpg)

Output:
![136-skycut](https://user-images.githubusercontent.com/4841220/34967332-b844e82a-fa16-11e7-881c-bc747f2db28f.png)

**Comment by wingarlo** [comment]
Using an algorithm that checks for greatest intensity drop, working downward on an image, I managed to get 48% accuracy when testing on "valid" images (out of the 35 images in "good-images" 17 attempted to crop out the landscape.)

Of these 17 images that did crop out the landscape (found in [this imgur album](https://imgur.com/a/WyIQ0)) we can see many landscapes (especially in the city images as well as images where water is only part of the landscape) did not get fully removed. 

By looking at the images that didn't pass the initial intensity drop test, I will adjust the minimum drop needed to pick up difficult to determine horizons while still not accepting invalid images. 

In [THIS](https://github.com/wingarlo/Aerolyzer/blob/106/aerolyzer/split-image-bgr-data) file on my local branch, I list the following:
```
image path
["greatest vertical intensity drop", "the pixel row the intensity drop is on"]
Top half b max 
Top half g max 
Top half r max 
Bottom half b max 
Bottom half g max 
Bottom half r max 
```
for each file tested. 

After altering the minimum intensity drop and testing it on more invalid images, the next step for classifying the images would be to compare the blue and red values on both the top and bottom half of the sky to determine if what is left after the crop is a sky during sunrise/sunset.

**Comment by wingarlo** [comment]
Moved to Issue #118
