### ISSUE TITLE
update pypi package

### ISSUE THREAD

**Issue by kwhitehall** [Aerolyzer/Aerolyzer#120]

**Comment by kwhitehall** [comment]
Still working on this. Butting some dependency issues with urllib and opencv-python based on version of Python.

**Comment by kwhitehall** [comment]
Ok @wingarlo and @RossDan96 This should be okay now. The version is 0.0.0.8. Please test that it works on your end with pip install.

**Comment by kwhitehall** [comment]
Ping @wingarlo and @RossDan96

**Comment by wingarlo** [comment]
Sorry for the delay.

We are either running into an installation problem or something is missing from the build. Some functions in the image restriction functions make calls to the yaml file in the config folder that is not there. Is the config folder also supposed to go with the rest of the installed files? We are getting this error when running the test-location python script: 
<img width="363" alt="config err" src="https://user-images.githubusercontent.com/17505393/38839556-134beffa-4190-11e8-821a-69eee9ecb216.png">

**Comment by kwhitehall** [comment]
The config folder doesn't go in with the files for the lib. Instead, the initialization class of aerolyzer should allow the user to pass in the location of the config files.
