### ISSUE TITLE
Image Restriction Pseudocode

### ISSUE THREAD

**Issue by jessehanson** [Aerolyzer/Aerolyzer#30]
Create pseudocode for the image restrictions in the upload process.

**Comment by kwhitehall** [comment]
@jessehanson Please make this file a python file, not a PDF as the language we are using is python. 
For the docstring with each function consider the following:
'''
Purpose:
Inputs:
Outputs:
Assumptions:
'''

**Comment by kwhitehall** [comment]
This has been addressed in PR #36
