### ISSUE TITLE
configure aerolyzer py package 

### ISSUE THREAD

**Issue by kwhitehall** [Aerolyzer/Aerolyzer#62]

**Comment by kwhitehall** [comment]
@jessehanson @colliell @liusop can you please confirm that you can install this code using `pip install aerolyzer`

**Comment by colliell** [comment]
@kwhitehall success for me!

**Comment by kwhitehall** [comment]
yaml library is missing

**Comment by kwhitehall** [comment]
numpy version must be higher than 1.7.2 otherwise conflicts with opencv

**Comment by lamki866** [comment]
@wingarlo Have you managed to get the import horizon library working correctly?

**Comment by lamki866** [comment]
Logan fixed it in #90

**Comment by lamki866** [comment]
Logan fixed it in #90
