### ISSUE TITLE
redacted

### ISSUE THREAD

**Issue by khlam** [Aerolyzer/Aerolyzer#85]
Logan and I will experiment with OpenCV horizon detection per our SDS.

**Comment by wingarlo** [comment]
Created a test python program able to access the aerolyzer python package

**Comment by kwhitehall** [comment]
@wingarlo was this test program addressed in PR #84?

**Comment by wingarlo** [comment]
Yes. We were testing adding modules and the test.py was renamed to horizon.py a few moments ago. I may have commented in the wrong PR though.

**Comment by khlam** [comment]
redacted

**Comment by kwhitehall** [comment]
@lamki866 what do you mean an image scraper? What are you scraping? Also, please explain what this PR (and related issue addresses)i.e. revised more details of the purpose and the algorithm. It maybe cleaner to open another issue and reference this one in it

**Comment by khlam** [comment]
redacted

**Comment by kwhitehall** [comment]
Thank you for the edits @lamki866, I now follow. Why isn’t it very accurate (according your description)? How did you determine accuracy? Do you have examples of where it is failing?

**Comment by khlam** [comment]
redacted

**Comment by lamki866** [comment]
Closing, made obsolete by #97. Continuing horizon discussion in #96
