### ISSUE TITLE
Pipeline Image Library to VM

### ISSUE THREAD

**Issue by lamki866** [Aerolyzer/Aerolyzer#86]
Our VM is a limited size and cannot accommodate a library large enough to characterize our classifier. Daniel will be designing a system to scrape images from Google Drive and other file services per our SDS.

**Comment by kwhitehall** [comment]
@lamki866 what are the specs of the VM?

**Comment by lamki866** [comment]
Current VM Specs: Ubuntu 16.04, 70 GB virtual HDD
Regarding the VM I have two goals:
- Shrink the VM's size for portability
- Move VM to cloud services

The block here is creating a development platform that scales to future needs. To prove our classifier API correctly identifies horizons requires a very large library of images. Currently we only know how to point our  classifier to look at a local directory on the VM or host computer for images. It would be more convenient and if we had a system that just streamed images to our VM  from a web location like Google Drive rather than downloading each image.

**Comment by kwhitehall** [comment]
Ok. Given the size of our images, I think that we should be able to prototype with the 70 GB space. This block should be considered a todo in the future. For now, you can suck the images into the VM and go from there. Furthermore, the functionality in the Django framework is to import the images locally and work from there. If the VM computation power isn’t enough, we can revisit this issue in this iteration. Thoughts?

**Comment by lamki866** [comment]
Sounds good to me!
