### ISSUE TITLE
Add yourselves to the team

### ISSUE THREAD

**Issue by kwhitehall** [Aerolyzer/Aerolyzer#88]
@lamki866 @wingarlo and @RossDan96 please add yourselves to the project. You should have received an email inviting you. You can also accept the invitation at https://github.com/Aerolyzer

**Comment by lamki866** [comment]
Thanks, I've accepted the invite. Would you like us to merge future pull requests into the main branch?

**Comment by wingarlo** [comment]
Accepted the invite

**Comment by kwhitehall** [comment]
@lamki866 no to merging future PRs unless explicitly asked to or 72hrs has elapsed

**Comment by kwhitehall** [comment]
Edit: 72 hrs have elapsed since opening the PR and no review is in progress

**Comment by RossDan96** [comment]
Forked the repo and accepted invite.

**Comment by kwhitehall** [comment]
Thanks all!
