### ISSUE TITLE
Tensorflow Testing

### ISSUE THREAD

**Issue by RossDan96** [Aerolyzer/Aerolyzer#93]
#92
Adding Docker work to folder Aerolyzer\misc\tensortesting
The bulk of this code is a copy of https://github.com/xblaster/tensor-guess that we want to test for comparison purposes.

**Comment by lamki866** [comment]
Is there a classifier included in #92 that has already been trained? Or is this just a docker image and test script that needs to be trained?

**Comment by RossDan96** [comment]
As of #92 it hasn’t been trained
