### ISSUE TITLE
Merged pull request. Removed test. 

### ISSUE THREAD

**Issue by wingarlo** [Aerolyzer/Aerolyzer#94]
Removed the wingarlo-test.txt

made changes to __init__.py, horizon.py, and test.py to test importing aerolyzer. 

Merged with my last pull request #90

**Comment by wingarlo** [comment]
I actually think I messed up. I meant to make a new pull request for my last push but accidentally merged with Aerolyzer.

**Comment by lamki866** [comment]
You're fine, go ahead and revert it from here: #90

**Comment by wingarlo** [comment]
Thanks, I reverted and sent pull request #95

**Comment by wingarlo** [comment]
addressed(?) in PR #95 which was closed as it was just a test
