### ISSUE TITLE
Create simple system to install required libraries

### ISSUE THREAD

**Issue by lamki866** [Aerolyzer/Aerolyzer#98]
In order to run the Aerolyzer library's Horizon detection, one must install OpenCV 3.3.0, Python 2.7.12, and Numpy 1.13.3. 

For ease of use, documentation, and consistency, I'm envisioning a PIP install system as outlined here: https://pip.pypa.io/en/stable/user_guide/
If PIP doesn't work then we'll need to find an alternative.

Ideally, all one would have to do to mimic the development environment would be to just clone the Aerolyzer repo and run `sudo pip install -r requirements.txt` or something.

**Comment by kwhitehall** [comment]
This point it moot. The aerolyzer library already uses pip install. As such, any requirements needed simply need to be added to the setup.py, so that when the aerolyzer library installs, it gets those requirements.

**Comment by kwhitehall** [comment]
I'm unassigning this task and opening the correct task to get this functionality done. @lamki866 I'll assign it to you.
